on: 
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'
    paths-ignore:
      - '**.css'
      - '**.tpl'
      - '**.txt'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.css'
      - '**.tpl'
      - '**.md'
      - '**.txt'
      - '**.yml'
      
name: Tests

jobs:
  php_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.1']
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        extensions: soap
        tools: composer, phpcs, phpunit:8.5.29
   
    - name: Check style/syntax
      run: phpcs

    - name: Run tests
      run: phpunit
